## A Data Analysis Project

##### Project Scenario

### Business Understanding

### Data Understanding

##### Loading the necessary python libraries

In [28]:
import numpy as np
import pandas as pd
import os
import pyodbc
from dotenv import load_dotenv
import warnings
warnings.filterwarnings('ignore')

##### Load the datasets

#### YEAR 2018

In [4]:
import pandas as pd
df_2018 = pd.read_csv('./Dataset/startup_funding2018.csv')

In [5]:
df_2018.head(20)

,Company Name,Industry,Round/Series,Amount,Location,About Company
0,TheCollegeFever,"Brand Marketing, Event Promotion, Marketing, S...",Seed,250000,"Bangalore, Karnataka, India","TheCollegeFever is a hub for fun, fiesta and f..."
1,Happy Cow Dairy,"Agriculture, Farming",Seed,"₹40,000,000","Mumbai, Maharashtra, India",A startup which aggregates milk from dairy far...
2,MyLoanCare,"Credit, Financial Services, Lending, Marketplace",Series A,"₹65,000,000","Gurgaon, Haryana, India",Leading Online Loans Marketplace in India
3,PayMe India,"Financial Services, FinTech",Angel,2000000,"Noida, Uttar Pradesh, India",PayMe India is an innovative FinTech organizat...
4,Eunimart,"E-Commerce Platforms, Retail, SaaS",Seed,—,"Hyderabad, Andhra Pradesh, India",Eunimart is a one stop solution for merchants ...
5,Hasura,"Cloud Infrastructure, PaaS, SaaS",Seed,1600000,"Bengaluru, Karnataka, India",Hasura is a platform that allows developers to...
6,Tripshelf,"Internet, Leisure, Marketplace",Seed,"₹16,000,000","Kalkaji, Delhi, India",Tripshelf is an online market place for holida...
7,Hyperdata.IO,Market Research,Angel,"₹50,000,000","Hyderabad, Andhra Pradesh, India",Hyperdata combines advanced machine learning w...
8,Freightwalla,"Information Services, Information Technology",Seed,—,"Mumbai, Maharashtra, India",Freightwalla is an international forwarder tha...
9,Microchip Payments,Mobile Payments,Seed,—,"Bangalore, Karnataka, India",Microchip payments is a mobile-based payment a...
10,BizCrum Infotech Pvt. Ltd.,"B2B, Shoes",Seed,—,"Delhi, Delhi, India",Building Transactionary B2B Marketplaces
11,Emojifi,Internet,Seed,—,"Bengaluru, Karnataka, India","Emojifi is an app that provides live emoji, st..."
12,Flock,"Apps, Collaboration, Developer Platform, Enter...",Seed,—,"India, Asia",Flock is a real-time messaging and collaborati...
13,Freshboxx,Food Delivery,Seed,—,"Hubli, Karnataka, India","Freshboxx is incubated at Sandbox Startups, a ..."
14,Wide Mobility Mechatronics,Industrial Automation,Seed,—,"Bangalore, Karnataka, India",Wide Mobility Mechatronics is a Private Compan...
15,Pitstop,"Automotive, Search Engine, Service Industry",Seed,"₹100,000,000","Bengaluru, Karnataka, India",Pitstop offers general repair and maintenance ...
16,Mihuru,"Finance, Internet, Travel",Seed,150000,"Mumbai, Maharashtra, India",Mihuru is an online platform which gives micro...
17,Fyle,"Accounting, Business Information Systems, Busi...",Seed,1100000,"Bengaluru, Karnataka, India",Fyle is an intelligent expense management plat...
18,AppWharf,"Artificial Intelligence, Product Search, SaaS,...",Seed,—,"New Delhi, Delhi, India",Appwharf is an intelligent assistant that help...
19,Antariksh Waste Ventures Pvt ltd,"Internet of Things, Waste Management",Seed,"₹500,000","Chennai, Tamil Nadu, India",Waste Management for Smart Cities

In [51]:
df_2018.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 526 entries, 0 to 525
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Company Name   526 non-null    object
 1   Industry       526 non-null    object
 2   Round/Series   526 non-null    object
 3   Amount         526 non-null    object
 4   Location       526 non-null    object
 5   About Company  526 non-null    object
dtypes: object(6)
memory usage: 24.8+ KB

##### YEAR 2019

In [2]:
import pandas as pd
df_2019 = pd.read_csv('./Dataset/startup_funding2019.csv')

In [3]:
df_2019.head(10)

,Company/Brand,Founded,HeadQuarter,Sector,What it does,Founders,Investor,Amount($),Stage
0,Bombay Shaving,NaN,NaN,Ecommerce,Provides a range of male grooming products,Shantanu Deshpande,Sixth Sense Ventures,"$6,300,000",NaN
1,Ruangguru,2014.0,Mumbai,Edtech,A learning platform that provides topic-based ...,"Adamas Belva Syah Devara, Iman Usman.",General Atlantic,"$150,000,000",Series C
2,Eduisfun,NaN,Mumbai,Edtech,It aims to make learning fun via games.,Jatin Solanki,"Deepak Parekh, Amitabh Bachchan, Piyush Pandey","$28,000,000",Fresh funding
3,HomeLane,2014.0,Chennai,Interior design,Provides interior designing solutions,"Srikanth Iyer, Rama Harinath","Evolvence India Fund (EIF), Pidilite Group, FJ...","$30,000,000",Series D
4,Nu Genes,2004.0,Telangana,AgriTech,"It is a seed company engaged in production, pr...",Narayana Reddy Punyala,Innovation in Food and Agriculture (IFA),"$6,000,000",NaN
5,FlytBase,NaN,Pune,Technology,A drone automation platform,Nitin Gupta,Undisclosed,Undisclosed,NaN
6,Finly,NaN,Bangalore,SaaS,It builds software products that makes work si...,"Vivek AG, Veekshith C Rai","Social Capital, AngelList India, Gemba Capital...",Undisclosed,NaN
7,Kratikal,2013.0,Noida,Technology,It is a product-based cybersecurity solutions ...,"Pavan Kushwaha, Paratosh Bansal, Dip Jung Thapa","Gilda VC, Art Venture, Rajeev Chitrabhanu.","$1,000,000",Pre series A
8,Quantiphi,NaN,NaN,AI & Tech,It is an AI and big data services company prov...,Renuka Ramnath,Multiples Alternate Asset Management,"$20,000,000",Series A
9,Lenskart,2010.0,Delhi,E-commerce,It is a eyewear company,"Peyush Bansal, Amit Chaudhary, Sumeet Kapahi",SoftBank,"$275,000,000",Series G

##### YEAR 2020

In [29]:
from dotenv import dotenv_values
import pyodbc

# Load environment variables from .env file
environment_variables = dotenv_values('.env')

# Access database credentials from environment variables dictionary
server = environment_variables.get("SERVER")
database = environment_variables.get("DATABASE")
password = environment_variables.get("PASSWORD")
username = environment_variables.get("USERNAME")

# Construct the connection string
connection_string = f"DRIVER=ODBC Driver 17 for SQL Server;SERVER={server};DATABASE={database};User Id={username};PASSWORD={password};"

In [30]:
print("USERNAME:", username)
print("PASSWORD:", password)

# Construct the connection string
connection_string = f"DRIVER=ODBC Driver 17 for SQL Server;SERVER={server};DATABASE={database};UID={username};PWD={password};"
# Connect to the database
try:
    connection = pyodbc.connect(connection_string)
    print("Connection successful!")
except Exception as e:
    print("Error:", e)

USERNAME: LP1_learner
PASSWORD: Hyp0th3s!$T3$t!ng

Connection successful!

In [31]:
# Specify the SQL queries to extract data from the tables
query_2020 = "SELECT * FROM dbo.LP1_startup_funding2020"
query_2021 = "SELECT * FROM dbo.LP1_startup_funding2021"

In [32]:
import warnings
import pandas as pd

# Suppress warnings
warnings.filterwarnings('ignore')

# Create a cursor from the connection
with connection.cursor() as cursor:
    # Execute the queries and fetch data into Pandas DataFrames
    df_2020 = pd.read_sql_query(query_2020, connection)
    df_2021 = pd.read_sql_query(query_2021, connection)

In [33]:
df_2020.head(10)

,Company_Brand,Founded,HeadQuarter,Sector,What_it_does,Founders,Investor,Amount,Stage,column10
0,Aqgromalin,2019.0,Chennai,AgriTech,Cultivating Ideas for Profit,"Prasanna Manogaran, Bharani C L",Angel investors,200000.0,None,None
1,Krayonnz,2019.0,Bangalore,EdTech,An academy-guardian-scholar centric ecosystem ...,"Saurabh Dixit, Gurudutt Upadhyay",GSF Accelerator,100000.0,Pre-seed,None
2,PadCare Labs,2018.0,Pune,Hygiene management,Converting bio-hazardous waste to harmless waste,Ajinkya Dhariya,Venture Center,NaN,Pre-seed,None
3,NCOME,2020.0,New Delhi,Escrow,Escrow-as-a-service platform,Ritesh Tiwari,"Venture Catalysts, PointOne Capital",400000.0,None,None
4,Gramophone,2016.0,Indore,AgriTech,Gramophone is an AgTech platform enabling acce...,"Ashish Rajan Singh, Harshit Gupta, Nishant Mah...","Siana Capital Management, Info Edge",340000.0,None,None
5,qZense,2019.0,Bangalore,AgriTech,qZense Labs is building the next-generation Io...,"Rubal Chib, Dr Srishti Batra","Venture Catalysts, 9Unicorns Accelerator Fund",600000.0,Seed,None
6,MyClassboard,2008.0,Hyderabad,EdTech,MyClassboard is a full-fledged School / Colleg...,Ajay Sakhamuri,ICICI Bank.,600000.0,Pre-series A,None
7,Metvy,2018.0,Gurgaon,Networking platform,AI driven networking platform for individuals ...,Shawrya Mehrotra,HostelFund,NaN,Pre-series,None
8,Rupeek,2015.0,Bangalore,FinTech,Rupeek is an online lending platform that spec...,"Amar Prabhu, Ashwin Soni, Sumit Maniyar","KB Investment, Bertelsmann India Investments",45000000.0,Series C,None
9,Gig India,2017.0,Pune,Crowdsourcing,GigIndia is a marketplace that provides on-dem...,"Aditya Shirole, Sahil Sharma","Shantanu Deshpande, Subramaniam Ramadorai",1000000.0,Pre-series A,None

In [16]:
df_2020.shape

(1055, 10)

In [18]:
df_2020.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1055 entries, 0 to 1054
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Company_Brand  1055 non-null   object
 1   Founded        842 non-null    float64
 2   HeadQuarter    961 non-null    object
 3   Sector         1042 non-null   object
 4   What_it_does   1055 non-null   object
 5   Founders       1043 non-null   object
 6   Investor       1017 non-null   object
 7   Amount         801 non-null    float64
 8   Stage          591 non-null    object
 9   column10       2 non-null      object
dtypes: float64(2), object(8)
memory usage: 82.5+ KB

In [19]:
df_2020.describe()

           Founded        Amount
count   842.000000  8.010000e+02
mean   2015.363420  1.130430e+08
std       4.097909  2.476635e+09
min    1973.000000  1.270000e+04
25%    2014.000000  1.000000e+06
50%    2016.000000  3.000000e+06
75%    2018.000000  1.100000e+07
max    2020.000000  7.000000e+10

In [20]:
df_2020.isnull().sum()

Company_Brand       0
Founded           213
HeadQuarter        94
Sector             13
What_it_does        0
Founders           12
Investor           38
Amount            254
Stage             464
column10         1053
dtype: int64

Hypothesis:
Hypothesis 1: The location (HeadQuarter) of a startup has an impact on its success or funding received.

Null Hypothesis (H0): The location of a startup's headquarters has no significant impact on the amount of funding it receives.

Alternative Hypothesis (H1): The location of a startup's headquarters is associated with a significant difference in the amount of funding it receives.

Analytical Questions:
1. Geographical Impact:

Is there a correlation between the location of a startup (HeadQuarter) and the funding it receives?
Are startups in specific regions more likely to receive higher funding?

2. Sector Analysis:

Which sectors (AgriTech, EdTech, Hygiene management, etc.) attract more funding on average?
Are certain sectors more likely to have successful startups?

3. Company Age and Funding:

Is there a relationship between the founding year of a company and the funding it receives?
Do newer startups tend to attract more funding?

4. Sector-wise What It Does Analysis:

How do the "What_it_does" descriptions vary across different sectors?
Are there common themes or patterns in what startups in specific sectors aim to achieve?

5. Success Factors:

Can we identify specific characteristics or patterns in successful startups (e.g., high funding) based on their provided information?
What factors contribute most to a startup's success in terms of funding?

In [40]:
df_2021.head(10)

,Company_Brand,Founded,HeadQuarter,Sector,What_it_does,Founders,Investor,Amount,Stage
0,Unbox Robotics,2019.0,Bangalore,AI startup,Unbox Robotics builds on-demand AI-driven ware...,"Pramod Ghadge, Shahid Memon","BEENEXT, Entrepreneur First","$1,200,000",Pre-series A
1,upGrad,2015.0,Mumbai,EdTech,UpGrad is an online higher education platform.,"Mayank Kumar, Phalgun Kompalli, Ravijot Chugh,...","Unilazer Ventures, IIFL Asset Management","$120,000,000",None
2,Lead School,2012.0,Mumbai,EdTech,LEAD School offers technology based school tra...,"Smita Deorah, Sumeet Mehta","GSV Ventures, Westbridge Capital","$30,000,000",Series D
3,Bizongo,2015.0,Mumbai,B2B E-commerce,Bizongo is a business-to-business online marke...,"Aniket Deb, Ankit Tomar, Sachin Agrawal","CDC Group, IDG Capital","$51,000,000",Series C
4,FypMoney,2021.0,Gurugram,FinTech,"FypMoney is Digital NEO Bank for Teenagers, em...",Kapil Banwari,"Liberatha Kallat, Mukesh Yadav, Dinesh Nagpal","$2,000,000",Seed
5,Urban Company,2014.0,New Delhi,Home services,Urban Company (Formerly UrbanClap) is a home a...,"Abhiraj Singh Bhal, Raghav Chandra, Varun Khaitan",Vy Capital,"$188,000,000",None
6,Comofi Medtech,2018.0,Bangalore,HealthTech,Comofi Medtech is a healthcare robotics startup.,Gururaj KB,"CIIE.CO, KIIT-TBI","$200,000",None
7,Qube Health,2016.0,Mumbai,HealthTech,India's Most Respected Workplace Healthcare Ma...,Gagan Kapur,Inflection Point Ventures,Undisclosed,Pre-series A
8,Vitra.ai,2020.0,Bangalore,Tech Startup,Vitra.ai is an AI-based video translation plat...,Akash Nidhi PS,Inflexor Ventures,Undisclosed,None
9,Taikee,2010.0,Mumbai,E-commerce,"Taikee is the ISO-certified, B2B e-commerce pl...","Nidhi Ramachandran, Sachin Chhabra",None,"$1,000,000",None